src/config/constants.ts, src/react-app-env.d.ts
(따로 이슈를 생성하진 않았습니다)
`.env` 파일 값에 대한 관리 방식을 좀 더 추가했습니다. 
- 타입을 정의해 `checkEnvVar` 함수의 타입을 강화했습니다.
- 기존 global NodeJS는 해치지 않고 extends를 활용해 유지했습니다.
=> [공통] Env파일 관리 방식 추가

.vscode/settings.json, src/index.tsx, src/page/Auth/FindPassword/SendAuthNumber/index.tsx, src/page/Auth/Signup/view/TermsOfServicePage/index.tsx, src/query/auth.ts, src/query/shop.ts, src/query/shopCategory.ts, src/query/shops.ts
쿼리 버전 업 PR에서 제가 수정한 부분 중 잘못된 부분이 있어서 해당 부분 정정 후 다시 PR 올립니다.
=> [공통] "React Query v3 -> v5 로 버전 업" 수정

src/query/auth.ts
- 사용자가 가게를 등록한 경우 `메인` 페이지로 이동
- 사용자가 가게를 등록하지 않은 경우 `상점 등록` 페이지로 이동하도록 수정했습니다.
=> [로그인] 회원 정보에 따른 페이지 이동 오류

src/page/ShopRegistration/hooks/CheckSameTime.ts, src/page/ShopRegistration/view/Mobile/Sub/index.tsx, src/page/ShopRegistration/view/PC/index.tsx
- **운영시간이 동일한 상태**에서 `전체 휴무`인 경우 수정
- **운영시간이 동일하지 않은 상태**에서 `전체 휴무`인 경우 수정
우선 떠오르는 문구가 없어서 `매일 휴무`라고 작성했는데, 더 좋은 글이나 방법있으면 알려주세요!
=> [가게 등록] 운영시간 휴무일 전체로 선택 시, 시간표에 undefined 나오는 버그 수정

src/page/ShopRegistration/constant/errorMessage.ts, src/page/ShopRegistration/view/Mobile/Main/Main.module.scss, src/page/ShopRegistration/view/Mobile/Main/index.tsx, src/page/ShopRegistration/view/Mobile/ShopCategory/ShopCategory.module.scss, src/page/ShopRegistration/view/Mobile/ShopCategory/index.tsx, src/page/ShopRegistration/view/Mobile/Sub/Sub.module.scss, src/page/ShopRegistration/view/Mobile/Sub/index.tsx, src/page/ShopRegistration/view/PC/index.tsx, src/store/shopRegistration.ts
- 가게 정보 입력 중 미기입 시 `에러 메시지` 출력 UI 추가
- 미 입력된 경우 다음으로 넘어가지 않음
- 휴대전화의 경우 `유효한 입력`에 대한 에러도 따로 관리함
=> [가게 등록] 가게 정보 기입 시 form 양식에 맞지 않는 경우 피드백 생성 추가

src/assets/svg/addmenu/mobile-single-menu-check-selected.svg, src/assets/svg/addmenu/mobile-single-menu-check.svg, src/page/AddMenu/components/AddMenuImgModal/index.tsx, src/page/AddMenu/components/MenuImage/MenuImage.module.scss, src/page/AddMenu/components/MenuPrice/MenuPrice.module.scss, src/page/AddMenu/components/MenuPrice/index.tsx, src/query/shop.ts
- 메뉴추가 후 내 상점 페이지 이동 후 메뉴 정보가 업데이트 되지 않던 문제 해결하였습니다.
=> fix: 메뉴추가후 내상점에 메뉴 업데이트 안되던 부분 수정

src/page/MyShopPage/components/ShopInfo/ShopInfo.module.scss, src/page/MyShopPage/components/ShopInfo/index.tsx
- 메인 페이지에 업로드 되지 않는 이미지들을 모두 고정된 이미지로 수정했습니다.
고정된 이미지를 임의로 정했기 때문에 고쳤으면 하는 부분 있으면 알려주세요!
=> [메인 페이지] 메인 페이지에 업로드 되지 않는 2개 이미지 변경

src/api/uploadFile/Uploadfile.ts, src/page/ShopRegistration/constant/errorMessage.ts, src/page/ShopRegistration/view/Mobile/Main/index.tsx, src/page/ShopRegistration/view/PC/index.tsx, src/utils/hooks/useImageUpload.ts
- 가게 등록에서 사진 넣을 때 에러 핸들링 추가
- 서버 보내기 전 `유효성 검사` 추가
=> 가게 등록에서 사진 넣을 때 에러 핸들링

src/page/AddMenu/components/MenuPrice/MenuPrice.module.scss, src/page/AddMenu/components/MenuPrice/index.tsx, src/page/AddMenu/index.tsx, src/query/shop.ts, src/store/addMenu.ts
- 단일 메뉴 선택시 옵션 선택 불가하게 하기
- 단일 메뉴로 가격만 보낼시 옵션 가격 null로 보내지는 오류 수정
=> fix: 메뉴 단일 메뉴 선택 로직 추가

src/page/AddMenu/components/AddMenuImgModal/AddMenuImgModal.module.scss, src/page/AddMenu/components/AddMenuImgModal/index.tsx, src/page/AddMenu/components/MenuImage/MenuImage.module.scss, src/page/AddMenu/components/MenuImage/index.tsx
- 이전 PR에서 만들어진 이미지 업로드 훅을 사용하도록 수정하였습니다.
=> Feature/#78  메뉴 추가 시 이미지 에러메시지 발생하도록 수정

src/api/shop/index.ts
- 상점의 모든 메뉴를 조회하기 위한 API 엔드포인트를 업데이트 했습니다.
[테스트 계정]
> ID : [znacici@naver.com](mailto:znacici@naver.com)
> PW: !haejin4610
- 테스트 결과 이상없이 작동합니다.
=> API 엔드포인트 변경에 따른 클라이언트 대응 - 상점의 모든 메뉴 조회

src/page/Auth/FindPassword/NewPassword/index.tsx, src/page/Auth/Login/index.tsx, src/page/Auth/Signup/utils/parseRegisterData.ts, src/query/register.ts, src/utils/ts/SHA-256.ts
=> feat: sha-256추가

src/page/Auth/Signup/hooks/useOwnerData.ts, src/page/Auth/Signup/view/OwnerDataPage/index.tsx, src/query/register.ts
=> 회원가입 존재하는 가게 shopId 추가

src/page/AddMenu/index.tsx
- 메뉴추가 pc 화면에서 취소 누르면 내 상점 페이지로 가도록 수정
=> fix: 메뉴추가 pc 화면에서 취소 누르면 내 상점 페이지로 가도록 수정

src/page/Auth/Signup/component/UserEmail/index.tsx, src/page/Auth/Signup/hooks/useTimer.ts, src/page/Auth/Signup/view/CompletePage/Complete.module.scss, src/query/register.ts
=> 회원가입 인증 완료 시 인증 코드 타이머 정지

src/page/Auth/FindPassword/SendAuthNumber/index.tsx
- 인증번호 발송 버튼 위치를 이메일 입력에서 인증번호 보내기로 옮겼습니다.
- 인증번호 보내기 라벨을 인증번호 입력으로 수정했습니다.
**수정 이전**
---
**수정 이후**
=> [비밀번호찾기] 인증번호 발송 버튼 위치 수정 및 라벨 수정

src/App.tsx, src/page/Auth/Login/static/option.ts, src/utils/constant/category.ts
- 아이디찾기 클릭 시 개발중 페이지로 이동하도록 라우팅 하였습니다.
- 상단바에서 가게정보 클릭 시 가게정보 페이지로 이동하도록 라우팅 하였습니다.
Close #125
=> 페이지 라우팅 수정

src/api/shop/index.ts, src/page/AddMenu/AddMenu.module.scss, src/page/ModifyMenu/index.tsx, src/query/menu.ts
메뉴삭제 기능을 추가했습니다.
UI가 나오지 않아 임의의 디자인으로 구현했습니다.
로직은 동작하기 때문에 추후 UI가 확정되면, UI만 수정하면 될 것 같습니다.
Close #137
=> [메뉴 삭제] 메뉴삭제 기능 구현

src/page/AddMenu/index.tsx, src/page/ModifyMenu/index.tsx, src/utils/hooks/useScrollToTop.ts
메뉴 수정, 추가 페이지로 이동시 스크롤이  초기화 되지 않는 문제를 해결하였습니다.
Close #139
=> feat: 메뉴 수정, 추가 페이지 스크롤 오류 수정

src/page/MyShopPage/MyShopPage.module.scss, src/page/MyShopPage/index.tsx
=> 메뉴 수정 버튼 삭제

src/page/MyShopPage/index.tsx
- `shop-registration` 에서 `store-registration`으로 수정했습니다.
- Close #148
=> 라우팅 url 수정

src/page/AddMenu/components/MenuName/MenuName.module.scss, src/page/AddMenu/components/MenuName/index.tsx, src/page/ModifyMenu/ModifyMenu.module.scss, src/page/ModifyMenu/index.tsx
메뉴 삭제 버튼 수정 버튼이 메뉴 추가 메이지에서도 나오는 버그 수정
Close #151
=> 메뉴 삭제 버튼 수정

src/page/ShopRegistration/view/PC/index.tsx
=> 배달가격 타입 숫자로 쓰도록 수정

src/page/AddMenu/components/AddMenuImgModal/index.tsx, src/page/AddMenu/components/MenuImage/index.tsx
모바일 환경에서 이미지 추가 모달 창의 카메라 촬영 기능 추가
Close #155
=> 카메라 촬영 버튼 동작 안함 수정

src/page/ModifyMenu/ModifyMenu.module.scss
메뉴 수정 페이지 bottom에 패딩을 줬습니다.
Close #157
=> 메뉴 수정 페이지 css 수정

src/page/MyShopPage/components/ShopInfo/index.tsx, src/page/ShopRegistration/component/TimePicker/index.tsx, src/page/ShopRegistration/hooks/useOperateTimeState.ts
=> 24시를 00시 00분으로 수정

src/page/MyShopPage/components/EditShopInfoModal/index.tsx
- 카테고리 아이디가 1(`전체보기`)인 경우만 따로 처리
Close #ISSUE_NUMBER
=> 카테고리 아이디가 1일 때 중복되는 에러 수정

src/page/ShopRegistration/view/PC/index.tsx
- 카테고리 아이디가 특정 상황에서 선택이 안되는 에러 수정
- useEffect의 의존성 배열에 `categoryId` 추가
Close #ISSUE_NUMBER
=> 카테고리 아이디 선택 안되는 에러 수정

.github/workflows/PICK_REVIEWER.yml, .github/workflows/reviewer.json, reviewers.json
- 기능 : 랜덤 리뷰어 기능
- issue : x
- PR 요청시 2명의 랜덤한 리뷰어 추가합니다.
- 1명은 내부 도메인 팀에서 추첨됩니다.
- 1명은 외부 도메인 팀에서 추첨됩니다.
=> 랜덤 리뷰어 기능 추가

src/page/AddMenu/hook/useMenuImageUpload.ts, src/utils/hooks/useImageUpload.ts
- Close #194
- 기능 : 단건 파일 업로드 API https:// 삭제
- issue : #194
- 백엔드 API 개선으로 인한 클라이언트 대응
**POST 단일 파일 요청 API는 올바르게 작동함**
=> 단건 파일 업로드에 대해 https:// 삭제

src/page/Auth/Signup/hooks/useOwnerData.ts
- 기능 : 회원가입 시 사진을 1개 이상 등록 가능하도록 변경
회원가입 시 최소 3개 이상의 사진을 등록해야 했지만 1개 이상 등록할 수 있도록 변경됨
=> [회원가입] 회원가입 시 사진을 1개 이상 등록 가능 하도록 변경

src/component/common/Header/index.tsx, src/page/Auth/Login/Login.module.scss, src/page/Auth/Login/index.tsx
- 기능 : 로그인 validation 및 헤더 수정
1. 모바일 화면에서 로그인 실패시 에러가 보이지 않는 현상을 수정했습니다.
2. 헤더 및 모바일 내 정보 페이지에서 가게 정보만 보이도록 수정했습니다. -> 추후 기능이 구현될 때마다 추가
=> Hotfix: 로그인 validation 및 헤더 수정

src/page/AddMenu/components/MenuPrice/MenuPrice.module.scss, src/page/AddMenu/components/MenuPrice/index.tsx, src/page/ModifyMenu/ModifyMenu.module.scss
- Close #215 
- 기능 : 단일 가격으로만 가격 등록하도록 변경
- issue : #215 
가격 input 가격 입력하는 것 하나 남기고 나머지 삭제
=> [주변상점] 가격추가 단일로만 가능하도록 변경 

src/page/MyShopPage/components/EditShopInfoModal/EditShopInfoModal.module.scss, src/page/MyShopPage/components/EditShopInfoModal/index.tsx, src/utils/constant/category.ts
- 가게 정보 수정 모달에서 `카테고리`를 추가했습니다.
- 피자 스쿨 사장님 홍보 할 때 피드백을 받아서 추가했습니다.
- 기능 : 가게 수정 모달에 `카테고리` 추가
- issue : 
[PC 뷰]
[Mobile 뷰]
- 급하게 수정하느라 디자인을 많이 신경 못썼는데, 수정사항 있으면 말해주세요!
=> [가게 정보 수정] 가게 정보 수정 모달 카테고리 추가

src/page/Coop/components/MenuCard/index.tsx, src/query/KeyFactory/coopKeys.ts, src/query/coop.ts
- Close #197 
- 기능 : 식단 이미지 업로드 기능 구현
- issue : #201 
- 식단 이미지 업로드에 presigned url이 적용되었습니다.
- 기존에 클라이언트와 서버상태로 관리되던 이미지 상태를 서버상태로만 관리하도록 수정했습니다.
https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/88afd65a-44fb-42c1-ac52-b15b57c8425d
=> [영양사] 식단 이미지 업로드 presigned-url 적용

src/query/auth.ts
- 기능 : 로그인 시 에러 메시지를 분기별로 처리하도록 수정
- issue : owner 로그인 실패 문의
=> [유저 로그인] 로그인 시 에러 메시지 분기별 처리

src/page/Coop/components/MenuCard/index.tsx
- Close #235
- 기능 : 이미지 업로드 버그 수정
- issue : #235 
이미지를 업로드 할 때 비동기처리를 하지 않아 생기는 버그를 수정했습니다.
=> [영양사] 이미지 업로드 버그 수정

src/page/Coop/Coop.module.scss, src/page/Coop/components/MenuCard/MenuCard.module.scss, src/page/Coop/components/MenuCard/index.tsx
- Close #242 
- 기능 : 다양한 크기의 기기에 대응합니다.
- issue : #242
- 가로가 400이하인 기기에서 사이드바가 약간 보이는 이슈를 해결합니다.
- 가로가 350이하인 기기에서 UI가 깨지는 이슈를 해결합니다.
=> [영양사] 반응형으로 다양한 기기 대응

src/global.d.ts, src/query/auth.ts
- 기능 : 전역 에러 타입 수정
- issue : #279 
- 전역 에러 타입 수정
- 강제 추론 로직 삭제 
cc. https://tanstack.com/query/latest/docs/framework/react/typescript#registering-a-global-error
=> [공통] 전역 에러 타입 수정

src/model/shopInfo/newMenu.ts, src/page/AddMenu/components/MenuPrice/MenuPrice.module.scss, src/page/AddMenu/components/MenuPrice/index.tsx, src/page/AddMenu/index.tsx, src/page/ModifyMenu/index.tsx, src/query/menu.ts
- Close #256 
- 기능 : 주변 상점 가격 input 수정
- issue : #256 
사이즈 가격에 대응하여 좀 더 직관적으로 사장님들이 사이즈를 추가할 수 있도록 변경하였습니다.
사이즈 추가 버튼 클릭시 사이즈와 가격 입력을 위한 input이 생성되고 메뉴 수정 시에는 사이즈가 있을 시 자동으로 사이즈 입력 모드로 입력을 받습니다.
=> [주변 상점] 가격 인풋 변경

src/App.tsx
- Close #269 
- 기능 : 라우트 가드제거
- issue : #269 
- 이것때문에 이슈였습니다.
=> [비밀번호 찾기 이후] 비밀번호 찾기 이후 로그인 화면으로 바로 넘어가는 문제 수정

src/page/Coop/components/MenuCard/index.tsx
- Close #289
- 기능 :갤러리에서 사진 선택하도록 변경
- issue : #289 
기존에는 카메라로 찍은 사진만을 올릴 수 있었는데, 갤러리에서도 선택할 수 있도록 변경하였습니다.
단, 모바일 크롬에서는 갤러리에서만 선택할 수 있습니다.
영양사님은 갤러리에서 사진을 선택하는게 편하다고 말씀하셨습니다.
=> [영양사] 갤러리에서 사진 선택하도록 수정

src/query/auth.ts
- Close #308 
- 기능 : 로그아웃 시 세션의 user_type 사라지도록
- issue : #308
로그아웃 시 세션의 user_type 사라지도록하는 동작을 추가했습니다.
=> [공통] 로그아웃 시 세션에 user_type 남아있는 문제

src/page/MyShopPage/components/EditShopInfoModal/index.tsx, src/utils/hooks/useImagesUpload.ts
- Close #307 
- 기능 : 가게 수정 시 이미지를 여러 장 등록할 수 있도록 수정
- issue : #307 
코드를 분석해 본 결과 imageFile을 imageUrl에 저장하는 방식으로 이미지가 등록되고 있었습니다
따라서 imageFile과 imageUrl을 동기화해주는 작업이 필요했습니다
=> [코인 오너] 가게 수정 시 이미지를 여러 장 등록할 수 있도록 수정

src/component/common/Auth/Complete/index.tsx, src/page/MyShopPage/components/EditShopInfoModal/index.tsx, src/page/MyShopPage/components/ShopInfo/index.tsx, src/page/ShopRegistration/component/Modal/Category/index.tsx, src/page/ShopRegistration/view/Mobile/ShopCategory/index.tsx, src/page/ShopRegistration/view/Mobile/ShopConfirmation/index.tsx, src/page/ShopRegistration/view/PC/index.tsx, src/store/shopRegistration.ts
- Close #313 
- 기능 : 가게 정보 입력 관련 에러 수정 및 카테고리 단일화
- issue : #313
기존 운영 시간은 일주일 중 첫 번째로 휴일이 아닌 날의 운영 시간을 가져오고 있었습니다.
이때 가게 정보 입력 시 모든 요일을 휴일로 등록하면 모든 날이 휴일이므로 운영 시간을 가져오지 못해서 에러가 발생했습니다
따라서 오늘 요일에 맞는 운영 시간을 보여주도록 변경했습니다.
모든 날을 휴일로 하는 경우는 특수한 경우지만 있을 수 있다고 판단했습니다.
그리고 카테고리를 정리하면서 가게마다 한 개의 카테고리를 가지도록 기획했으므로
가게마다 한 개의 카테고리를 가지도록 수정했습니다.
마지막으로 가게 등록 시 이미지가 등록 안되는 오류를 수정했습니다.
=> [코인 오너] 가게 정보 입력 관련 에러 수정 및 카테고리 단일화

src/page/Coop/components/Calendar/Calendar.module.scss, src/page/Coop/components/MenuCard/MenuCard.module.scss, src/page/Coop/components/MenuCard/index.tsx, src/page/Coop/components/SoldoutToggle/SoldoutToggle.module.scss
- Close #315
- 기능 : 캠퍼스팀 QA 이슈 해결
- issue : #315 
- 오버레이 radius 누락 수정
- 스트로크 라운딩 수정
- 사진과 글자 사이 간격 수정
- 애플 기본 폰트색 이슈 대응
- 사진이 없을 때 품절시 품절 레이아웃만 보이도록 수정
- 주간탭 버튼 폰트크기 수정
=> [영양사] 캠퍼스팀 2차 스프린트 QA 이슈 해결

src/query/auth.ts
- 기능 : 에러 상태 코드 400으로 수정
- issue :
=> [로그인] 에러 상태 코드 수정

src/page/MyShopPage/components/EventTable/components/EventCard/index.tsx
=> [주변상점] 이벤트이미지 에러 hotfix

src/component/common/Auth/PreviousStep/index.tsx, src/page/Auth/Signup/component/ErrorMessage/ErrorMessage.module.scss, src/page/Auth/Signup/view/TermsOfServicePage/TermsOfService.module.scss, src/page/ShopRegistration/view/Mobile/ShopEntry/ShopEntry.module.scss, src/page/ShopRegistration/view/Mobile/index.tsx, src/utils/constant/menu.ts
- 기능 : QA 이슈 해결
처음 가게 정보 기입 시 뒤로가기 버튼 삭제
회원가입 오류 CSS 수정
회원가입 버튼 위치 수정
메뉴 카테고리 순서 추천 -> 메인 -> 세트 -> 사이드로 수정

=> [주변상점] QA이슈 해결

src/page/MyShopPage/components/EventTable/components/EventCard/index.tsx
- 기능 : 이벤트 날짜 UI 수정
이벤트 날짜를 시작일과 종료일이 나오도록 수정
=> Hotfix 이벤트 날짜 UI 수정

src/index.scss
- Close #335
- 기능 : iOS 기본폰트 색상 대응
- issue : #335
iOS 기본폰트 색상이 파란색이여서 전역적으로 검정색으로 적용해줬습니다.
배포 후 캐시삭제하고 iOS환경에서 직접 확인 할 수 있습니다.
=> [공통] iOS 폰트색상 전역적으로 수정 

public/index.html
- 기능 : 구글 gtag script 추가
- issue : #
- 구글 gtag script가 없어 로그를 추적할 수 없는 문제가 있어 추가하였습니다.
=> [DA 구글 태그] 구글 태그 script 추가

src/page/AddMenu/components/MenuPrice/components/PriceInput/index.tsx, src/page/AddMenu/index.tsx, src/page/ModifyMenu/index.tsx
- 기능 : 메뉴 추가가 안되는 현상 수정
- issue : #
모바일 에서 메뉴 추가 버튼 클릭 시 modal에서 메뉴 추가를 완료했어야 하는데 정작 모바일에서 모달이 보이지 않았음.
원래 작성자 의도가 모달을 pc버전에서 띄우는 것으로 예상하고 pc버전에서 modal을 통해 메뉴 추가를 완료하고 모바일에서는 바로 메뉴가 추가되도록 변경했습니다.
메뉴 추가와 수정의 플로우를 맞췄습니다. (pc는 modal을 띄우고 모바일은 바로 수정되는 방식)
=> [비즈니스] 메뉴 추가가 안되는 현상 수정

src/page/Auth/Signup/components/ownerInfoStep/index.tsx, src/page/Auth/Signup/components/ownerInfoStep/ownerInfoStep.module.scss, src/page/Auth/Signup/components/phoneStep/index.tsx, src/page/Auth/Signup/components/phoneStep/phoneStep.module.scss, src/page/Auth/Signup/components/searchShop/searchShop.module.scss, src/page/Auth/components/Done/index.module.scss, src/page/Auth/components/Done/index.tsx
- Close #362
- 기능 : css오류, 로그인페이지 바로가기 오류, 파일삭제 오류 수정
- issue : #362 
다음 버튼 가려지는 css 수정
로그인 페이지 바로가기 추가
파일 삭제 오류 수정
전화번호 11자리 제한 추가
=> [주변상점] css오류, 로그인페이지 바로가기 오류, 파일삭제 오류 수정

src/page/Auth/FindPassword/Verify/index.tsx, src/page/Auth/Signup/components/agreeStep/agreeStep.module.scss, src/page/Auth/components/Common/index.module.scss, src/page/Auth/components/Done/index.module.scss, src/page/MyShopPage/components/BankList/index.tsx, src/query/auth.ts
- 기능 :  비즈니스팀 QA 반영
- issue : #
회원가입에서 다음 버튼이 이용약관을 가리는 현상  수정
비밀번호 변경 시 인증되었습니다 문구 추가 및 인증 성공 시 input disable 삭제
로그인 바로 가기 버튼 높이 조정
계좌번호 등록 시 하이픈을 필수값에서 제외
=> [비즈니스] 비즈니스팀 QA 반영

src/page/Auth/Login/Login.module.scss, src/page/Auth/Login/index.tsx, src/page/ShopRegistration/view/PC/ShopConfirmation/index.tsx
- 기능 : validation 추가
- issue : #
- validation 몇 가지 추가했습니다.
- 리코드 참고해서 반영했지만 문구가 어색하면 피드백 부탁드립니다.
- 추가적으로 이전에 음식점 추가 시에 가게 검색 부분을 제거하기로 했어서 제거했습니다.
- [관련 슬랙](https://bcsdlab.slack.com/archives/C06N99Z3D45/p1718370171960809)
=> [비즈니스] validation 수정

src/component/Auth/PreviousStep/PreviousStep.module.scss, src/component/Auth/PreviousStep/index.tsx, src/component/Auth/SubTitle/SubTitle.module.scss, src/model/shopInfo/allShopInfo.ts, src/model/shopInfo/myShopInfo.ts, src/page/MyShopPage/components/EditShopInfoModal/index.tsx, src/page/ShopRegistration/view/Mobile/Main/Main.module.scss, src/page/ShopRegistration/view/Mobile/Main/index.tsx, src/page/ShopRegistration/view/Mobile/ShopCategory/ShopCategory.module.scss, src/page/ShopRegistration/view/Mobile/ShopCategory/index.tsx, src/page/ShopRegistration/view/Mobile/ShopConfirmation/ShopConfirmation.module.scss, src/page/ShopRegistration/view/Mobile/ShopConfirmation/index.tsx, src/page/ShopRegistration/view/Mobile/ShopRegistrationComplete/ShopRegistrationComplete.module.scss, src/page/ShopRegistration/view/Mobile/ShopRegistrationComplete/index.tsx, src/page/ShopRegistration/view/Mobile/ShopRegistrationMobile.module.scss, src/page/ShopRegistration/view/Mobile/Sub/Sub.module.scss, src/page/ShopRegistration/view/Mobile/Sub/index.tsx, src/page/ShopRegistration/view/Mobile/index.tsx
- 기능 : 사장님 모바일 뷰 UX 개선
- issue : #
- 전체적인 UX 위치를 개선하였고, 하단 버튼을 개선하였습니다.
https://github.com/user-attachments/assets/fdff1036-3fc5-41ab-8081-a0c279a5823a
=> [UX 개선]: 사장님 가게 등록 UX 개선

src/component/common/Header/MobilePanel/index.tsx, src/component/common/Header/index.tsx, src/component/common/TimeDialPicker/TimeDialPicker.module.scss, src/component/common/TimeDialPicker/index.tsx, src/page/ManageEvent/AddingEvent/index.tsx, src/page/MyShopPage/components/EditShopInfoModal/EditShopInfoModal.module.scss, src/page/MyShopPage/index.tsx, src/page/ShopRegistration/component/Modal/Calender/component/YearMonthSelectModal/index.tsx, src/page/ShopRegistration/view/Mobile/Sub/Sub.module.scss
qa 이슈 수정
1. 날짜 미 선택 시 모달
2. 이벤트 탭인 경우 메뉴 수정 버튼 비활성화
3. 이벤트 추가,수정 헤더 추가
4. 운영 시간 줄넘긴 이슈 수정
=> fix : 캘린더 제외 qa 수정

src/page/AddMenu/components/MenuImage/index.tsx, src/page/ManageEvent/AddingEvent/index.tsx, src/page/MyShopPage/components/ShopInfo/ShopInfo.module.scss, src/page/MyShopPage/components/ShopInfo/index.tsx, src/page/MyShopPage/hooks/useShopTimeInfoMapping.tsx, src/page/ShopRegistration/component/Modal/Calender/Calender.module.scss, src/page/ShopRegistration/component/Modal/Calender/calender.css, src/page/ShopRegistration/component/Modal/Calender/index.tsx, src/page/ShopRegistration/hooks/useOperateTimeState.ts, src/page/ShopRegistration/view/Mobile/ShopConfirmation/ShopConfirmation.module.scss
- 기능 :  qa이슈 해결
- issue : #
1. 캘린더 시작일은 단일, 종료일은 범위로 선택하도록 수정
2. 메뉴 이미지 3개 제한 에러 수정
3. 운영시간 줄넘김 에러 수정
4. 평일, 주말 묶어서 보여주기 요구사항 적용
1.
=> [비즈니스] 마지막 qa 이슈 해결

src/component/common/CustomModal/index.tsx, src/component/common/Modal/alertModal/index.tsx, src/lib/gtag.ts, src/page/AddMenu/components/AddMenuImgModal/index.tsx, src/page/AddMenu/components/MenuImage/index.tsx, src/page/AddMenu/index.tsx, src/page/ManageEvent/AddingEvent/index.tsx, src/page/MyShopPage/components/EditShopInfoModal/index.tsx, src/page/MyShopPage/components/EventTable/index.tsx, src/page/MyShopPage/components/ShopInfo/index.tsx, src/page/MyShopPage/index.tsx, src/utils/hooks/useLogger.ts
- 기능 : 
- issue : #
라이브러리에 따라 작성 되었던 gtag 및 로깅 훅의 속성명을
코인 프로젝트에 맞게 직관적으로 수정했습니다. 
코인 웹 레포지토리의 명명을 따라갔습니다.
actionTitle -> team
title -> event_category
=> [로깅] 로깅 속성 이름 수정
