src/api/auth/index.ts, src/api/index.ts, src/layout/AuthLayout/index.tsx, src/page/Auth/FindPassword/NewPassword/index.tsx, src/page/Auth/FindPassword/SendAuthNumber/SendAuthNumber.module.scss, src/page/Auth/FindPassword/SendAuthNumber/index.tsx, src/page/Auth/FindPassword/hooks/useRouteCheck.ts, src/page/Auth/Login/index.tsx, src/query/auth.ts
- 테스트계정
email: mingu830@gmail.com
pw: mingu980!
- 토큰없음 에러가 발생하지 않아야 할 때도 발생하는 문제를 해결했습니다. feat @ChoiWonBeen 
추후 setUser가 에러를 다루는 문제를 제거해야 한다고 합니다.
- 인증번호 발송 및 검증하여 새로운 비밀번호 변경 페이지까지 이동하도록 구현했습니다.
- 새 비밀번호 입력 페이지랑 분리하여 PR 올리도록 하겠습니다.
- 기존 figma디자인은 인증번호 보내기 `input` 옆에 인증번호 발송 `button`이 있었으나, 이메일 입력 `input` 옆에 있는것이 자연스러울 것 같아 수정했습니다.
- 인증번호 발송 눌렀을 때, 잘못된 인증번호를 입력했을 때 메시지가 필요해 보이는데 다음 PR때 반영하겠습니다.
=> [비밀번호 찾기] 인증번호 발송 및 검증 로직 구현

src/page/ShopRegistration/constant/errorMessage.ts, src/page/ShopRegistration/view/Mobile/Main/index.tsx, src/page/ShopRegistration/view/PC/index.tsx, src/utils/hooks/useImageUpload.ts
- 가게 정보 기입 완료 후 이미지 구현 완료
확인 방법
1. 본인 계정에 가게가 이미 등록 되어 있는 경우 `src/query/auth.ts`에 **32,33번 줄**안에 `/store-registration`로 수정
2. 로그인 후 가게 정보 기입
3. 메인 화면에서는 제일 첫 번째 shop이 나오기 때문에 `src/query/shop.ts`에 **21번째** 줄의 숫자를 변경해가면서 확인 가능
번거롭지만 기능이 잘 되는지 확인 부탁드립니다!
=> [가게 등록] 가게 정보 기입 완료 후 이미지가 메인 화면에 표시 안됨

src/page/AddMenu/index.tsx
모바일뷰에서 취소 버튼 누르면 메인 페이지로 가도록 수정했습니다.
=> fix: 모바일뷰 취소 버튼 누르면 메인 페이지로 가도록 수정

src/page/ShopRegistration/view/Mobile/ShopConfirmation/ShopConfirmation.module.scss
- 가게 정보 확인 중 결제 옵션 `마우스 포인터` 삭제
=> [가게 등록] 모바일 가게 정보 확인 중 결제 옵션 마우스 포인터 삭제

src/page/AddMenu/index.tsx
모발일화면에서 확인 버튼을 누르면 새로 생성한 메뉴정보를 추가하고 메인 상점 페이지로 넘어가도록 수정
=> fix: 모바일 화면 확인 누르면 동작하도록 수정

src/page/MyShopPage/components/ShopInfo/ShopInfo.module.scss, src/page/MyShopPage/components/ShopInfo/index.tsx
- 가게명이 길면 #배달가능 #카드가능 #계좌이체 가능 키워드가 넘치는 버그를 수정했습니다.
- 가게명이 길어도 기타정보가 다음주로 넘어가지 않도록 했습니다.
- 모바일환경에서 가게명이 길어서 다음줄로 넘어갈 때 가게명이 겹치는 버그를 수정했습니다.
- 모바일환경에서 가게 정보 수정 버튼 width를 약간 줄였습니다.
=> 가게명이 길면 글자가 넘치는 버그 수정

src/page/AddMenu/components/MenuCategory/MenuCategory.module.scss, src/page/AddMenu/components/MenuCategory/index.tsx, src/page/AddMenu/index.tsx, src/store/addMenu.ts
- 서버측 에러 메시지를 이용하여 에러핸들링을 하고 싶었지만 다음과 같은 문제가 있었습니다.
내 상점으로 이동하면서 서버측에 post 요청을 보내게 되고 에러메시지를 반환 받는거라, 메뉴추가가 되었다는 메시지가 발생하고 에러메시지를 띄울 수 있게 되는데, 이는 적절치 못한 에러 핸들링이라고 생각했습니다.
따라서 메뉴추가 화면에서 확인버튼을 누르기 전에 에러핸들링이 필요하다고 판단했습니다.
- 카테고리가 선택되지 않으면 ```카테고리를 1개 이상 선택해주세요```에러 메시지를 하단에 띄웁니다.
=> 카테고리를 미 선택한 경우에도 메뉴추가 진행이 되던 버그 수정

src/page/AddMenu/components/MenuCategory/index.tsx, src/page/AddMenu/components/MenuName/MenuName.module.scss, src/page/AddMenu/components/MenuName/index.tsx, src/page/AddMenu/hook/useFormValidation.ts, src/page/AddMenu/index.tsx, src/store/addMenu.ts, src/store/addMenuErrorMessageStore.ts
- 메뉴추가시 메뉴명 입력이 필수이지만 공백으로 메뉴추가를 하여도 메뉴추가가 진행되던 버그를 수정했습니다.
이슈와 다르게 가격정보의 경우 서버측에서 입력을 필수로 하고있지 않아, 메뉴명만 필수적으로 입력하도록 하였습니다.
가격에서 사이즈의 경우 입력하지 않을경우 메뉴명이 들어가며, 가격의 경우 입력하지 않을경우 0원이 들어갑니다.
- 추가적으로 순환구조로 인해 발생하던 eslint 에러를 해결하기 위해 순환로직을 분리하여 별도의 파일로 만들었습니다.
이외에도 방대해지는 로직의 경우 별도의 Hook으로 분리했습니다.
Close #107
=> 메뉴추가시 메뉴명을 필수적으로 입력하도록 수정

src/page/MyShopPage/index.tsx
- 기존에는 가게 정보 기입 과정에서 주소창을 루트`/`로 수정하거나, 특수한 경우에 가게정보 페이지로 이동할 수 있는 버그가 있었습니다.
가게정보 페이지에서 가게정보가 없을 시 강제로 가게정보기입 페이지로 이동시키는 로직을 추가했습니다.
Close #109
=> 상점 등록을 하지 않아도 메뉴 추가로직이 실행되는 버그 수정

src/App.tsx, src/page/MyShopPage/index.tsx, src/query/shop.ts
이전 #110 의 문제를 해결했습니다.
> shopData를 이용하여 기능을 구현하려고 시도했으나, 해당 응답에서 가게정보가 있을 때도 undefined를 응답으로 받고 정상적인 가게정보를 응답으로 받아 가게정보가 있는경우와 없는 경우를 구분할 수 없었습니다.
정상적인 API호출 시에도 undefined가 수신되는 문제는 비동기처리 문제로 추정되나, 도저히 구체적인 원인을 찾을 수가 없어, getMe에서 가게 갯수를 응답으로 받아 해당기능을 구현했습니다.
데이터가 있음에도 undefined가 발생한 이유는 react-query의 경우 로딩중일 때 데이터가 undefined가 됩니다.
이를 방지하기 위해 `!shopData && !isLoading`을 사용했음에도 `{shopData} = useQuery()` 의 `enabled: !!shopId` 에서 shopId의 데이터를 기다리는 동안 isLoading이 false가 되어 `!shopData && !isLoading` 조건이 만족되어버리는 문제가 있었습니다.
즉, `shopData`가 없어서 undefined인 경우와 로딩중이여서 undefined인 경우를 구분하기가 어려운 문제가 있었습니다.
로딩중일 때 undefined인 경우를 해결하기 위해 `myShop()`을 호출할 때 `useSuspenseQuery`를 사용하여 API호출이 끝나야 데이터를 가지도록 수정하였습니다.
결론적으로 `shopData`가 없는 경우에만 undefined가 발생하도록 하여 `shopData`로 에러핸들링을 하도록 하였습니다.
Close #112
=> 상점등록을 하지 않아도 가게정보로 이동가능한 버그 수정 리팩토링

src/page/MyShopPage/index.tsx
- "/"페이지로 이동 시 모든 메뉴 데이터 초기화 되도록 하여 뒤로가기나 코인 로고 클릭으로 메인 페이지 이동시 전역 데이터 초기화를 하도록 하였습니다.
Close #123
=> fix: "/" 페이지로 이동시 모든 메뉴 데이터 초기화 되도록 수정

src/model/auth/index.ts, src/page/AddMenu/components/MenuCategory/index.tsx, src/page/AddMenu/components/MenuName/index.tsx, src/page/AddMenu/hook/useFormValidation.ts, src/page/AddMenu/index.tsx, src/page/Auth/Login/index.tsx, src/query/auth.ts, src/store/errorMessageStore.ts
로그인시 발생할 수 있는 다양한 에러상황에 따라 적절한 에러메시지가 출력되도록 수정하였습니다.
기존에는 일괄적으로 `아이디 또는 비밀번호를 잘못 입력했습니다`가 출력되었으나, 다양한 에러상황이 존재하여, 서버에서 제공하는 에러메시지를 출력하도록 하였습니다.
가입승인이 되지않은 경우 - 권한이 없습니다.
비밀번호가 일치하지 않는 경우 - 비밀번호가 일치하지 않습니다.
아이디가 일치하지 않는 경우 - 회원이 존재하지 않습니다.
**수정 이전**
---
**수정 이후**
Close #115
=> 로그인시 상황에 맞는 에러메시지가 표시되도록 수정

package.json, src/App.tsx, src/component/common/Toast/index.tsx, src/page/MyShopPage/components/EditShopInfoModal/EditShopInfoModal.module.scss, src/page/MyShopPage/components/EditShopInfoModal/index.tsx, src/page/MyShopPage/components/ShopInfo/ShopInfo.module.scss, src/page/MyShopPage/components/ShopInfo/index.tsx, src/page/MyShopPage/index.tsx, src/page/ShopRegistration/component/Modal/OperateTimePC/index.tsx, src/page/ShopRegistration/view/Mobile/Main/index.tsx, src/utils/ts/showToast.ts, yarn.lock
- 가게명 - 주소정보를 브라우저가 id-password로 인식하지 않도록 수정
- 휴무일이 없는 경우 `휴무일 없음`으로 수정
- 가게 정보 수정과 내 상점의 `가게 메인 사진`에 `object-fit` 추가
- 휴무를 true에서 false로 변경하면 00:00으로 초기화되는 로직 삭제
- 가게 정보 수정 후 액션 추가
- 알림을 표현하기 위해서 쩝쩝박사에서 사용하는 `react-toastify` 라이브러리를 새로 추가했습니다.
- 각각의 에러 수정 사항은 커밋 내용을 확인하면 더욱 빠르게 확인할 수 있습니다!
Close #127
=> 가게 정보 수정 에러 해결

src/page/Auth/Signup/view/OwnerDataPage/OwnerData.module.scss, src/page/MyShopPage/components/CatagoryMenuList/CatagoryMenuList.module.scss
- 회원가입의 가게명 마진을 수정했습니다.
- 가게정보에서 메뉴명이 길 때 가격과 겹치는 이슈를 해결했습니다.
- 메뉴에 하단 마진을 추가했습니다.
Close #128
=> [회원가입, 가게정보] CSS 이슈 수정

src/page/MyShopPage/components/ShopInfo/ShopInfo.module.scss
내 상점 페이지 메인 사진 가로 길이 넘침으로 인해 생기는 css 오류를 수정했습니다.
<수정 전>
<수정 후>
Close #141
=> fix: 내상점 페이지 모바일 뷰 css 오류 수정

src/page/AddMenu/AddMenu.module.scss, src/page/AddMenu/components/MenuName/MenuName.module.scss, src/page/AddMenu/components/MenuName/index.tsx, src/page/ModifyMenu/index.tsx, src/page/MyShopPage/components/ShopInfo/ShopInfo.module.scss
- 가게정보 이미지가 넘쳐서 헤더를 가리는 문제를 수정했습니다.
- 모바일 환경에서 메뉴 삭제 버튼이 취소, 수정버튼과 비슷한 위치에 있어 잘못 누를 가능성을 줄이고자 상단으로 이동했습니다.
- Close #144
=> 메뉴 삭제 버튼 이동, 가게정보 이미지 넘침 현상 수정

src/page/AddMenu/components/MenuPrice/index.tsx
단일 가격 시에 메뉴 추가 버튼을 클릭하면 옵션 가격 입력할 수 있도록 수정하였습니다.
Close #160
=> 메뉴 가격 추가 버튼 기능 수정

src/page/MyShopPage/components/EditShopInfoModal/index.tsx
- 상점 카테고리 아이디가 사라지는 에러 수정했습니다.
가게 수정 시 카테고리 아이디가 지워지지 않도록 변경하였습니다.
https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/acb44253-f1d4-4483-889d-3159cfd925e2
Close #169
=> fix: 상점 카테고리 아이디가 사라지는 에러 수정

src/page/Auth/Signup/utils/parseRegisterData.ts
- Close #194 
- 기존에 https가 포함되어 있는 내용 삭제했씁니다.
- 기능 : 
- issue :
=> [hotfix] https 삭제

src/component/common/Header/index.tsx, src/page/AddMenu/components/MenuName/MenuName.module.scss, src/page/AddMenu/components/MenuName/index.tsx, src/page/ShopRegistration/constant/errorMessage.ts, src/page/ShopRegistration/view/Mobile/ShopConfirmation/index.tsx, src/page/ShopRegistration/view/Mobile/Sub/index.tsx, src/page/ShopRegistration/view/PC/index.tsx, src/query/auth.ts
- Close #211 
- 기능 : 가게정보 입력 step 초기화
- issue : #211 
- 회원가입 이후 '가게 정보 기입' 화면이 나타나도록 변경하였습니다.
- '가게 정보 기입'의 대표자명을 제거했습니다.
- '메뉴 추가' 모바일 화면에서 메뉴명 미기입 에러 추가했습니다.
=> [#211] 로그인 플로우 해결

src/page/Auth/Login/index.tsx, src/page/MyShopPage/components/EditShopInfoModal/index.tsx, src/page/ShopRegistration/view/Mobile/Sub/index.tsx, src/query/auth.ts, src/store/errorMessageStore.ts
- Close #230 
- 기능 : 승인 모달 수정
- issue : #230 
- 이전 code를 이용해 모달 창 띄우는 것을 status 값으로 변경했습니다.
- 배달 금액 숫자만 입력 되도록 변경했습니다.
=> Fix: 모달 창 안 뜨는 문제 해결

src/page/Coop/components/MenuCard/index.tsx, src/page/Coop/components/SoldoutToggle/SoldoutToggle.module.scss
- Close #246
- 기능 : 모바일 크롬에서 사진촬영이 가능하도록 수정
- issue : #246
- 기존 모바일 크롬에서는 사진촬영이 불가능하고 갤러리에서 기존 사진을 선택만 할 수 있는 문제를 수정했습니다.
local환경을 모바일에서 직접 테스트 할 방법이 없어 병합 후 스테이지 서버에서 테스트해보겠습니다.
=> [영양사] 모바일 크롬에서 사진촬영이 불가능한 이슈 수정

src/page/ShopRegistration/view/Mobile/ShopConfirmation/index.tsx, src/query/shop.ts
- 기능 :  관리자 승인 후 로그인 시 가게 등록이 안되던 문제 수정
가게등록 시 useMyShop에서 카테고리를 받아오는데 이때 myShop이 호출되면서 
myShop.shops[0].id; 에서 에러가 발생함
이것을 수정했습니다
그리고 가게등록 후 가게 정보를 다시 받아오도록 수정했습니다
=> 관리자 승인 후 로그인 시 가게 등록이 안되던 문제 수정

src/page/Coop/components/MenuCard/index.tsx, src/page/Coop/components/SoldoutToggle/index.tsx
- Close #275
- 기능 : 품절 취소 기능 버그 수정
- issue : #275
A,B,C코너가 품절이 되고, C코너, B코너, A코너 순으로 품절취소를 했을 때 C,B,A순서가 아닌 A,B,C 순서로 품절취소가 되던 버그를 수정했습니다.
https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/b5fbd2a4-c75d-4876-922a-0222579c9fd8
=> [영양사] 품절취소기능 버그 수정

src/page/ModifyMenu/index.tsx, src/query/menu.ts
- Close #256 
- 기능 : 가격 input 오류 대응
- issue :  #256
이전 리뷰에서 refetch에서 refetchOnWindowFocus로 변경하였는데 동작하지 않아 다시 refetch 추가
=> hotFix: refech로 회귀

src/index.tsx
- Close #296 
- 기능 :  queryClient 재정의
- issue :  #296 
기존 queryClient 설정을 보면  refetchOnMount가 false로 지정되어 있어 쿼리 무효화를 시켜서 데이터가 stale상태가 되어도 refect가 안되는 경우가 있었습니다. 이 값을 true로 바꿔서 invalidationQueries가 원하는대로 동작하도록 수정했습니다.
또한 추가로 refetchOnWindowFocus, refetchOnReconnect도 false인 점이 불필요하다고 판단되어 true로 수정했습니다.
기존에 invalidation이 동작하지 않아서 refetchQueries 또는 useQuery의 refetch를 사용하신 부분이 많이 있을 겁니다.
자신이 수정했던 부분을 기억하셔서 불필요한 refetch가 이루어지지 않는지 다들 한번씩 확인 부탁드리겠습니다
=> [공통] 데이터가 stale일때 refetch 되도록 수정

src/page/Coop/components/MenuCard/index.tsx
- Close #291
- 기능 : 품절취소 모달창 구현
- issue : #291
- 기존 품절 모달창 내용 수정
- 품절 취소 모달창 구현
=> [영양사] 품절취소 모달 구현

src/page/AddMenu/components/AddMenuImgModal/index.tsx, src/page/AddMenu/components/MenuImage/index.tsx, src/page/ManageEvent/AddingEvent/index.tsx, src/page/ManageEvent/ModifyEvent/index.tsx, src/page/ManageEvent/index.module.scss, src/page/ModifyMenu/index.tsx, src/store/addMenu.ts, src/utils/hooks/useImagesUpload.ts
- Close #330 
- 기능 : 이벤트, 메뉴 관련 이슈 수정
- issue : #330 
1. 이벤트 추가, 수정 시 일반 텍스트를 입력하도록 변경했습니다
2. 메뉴 추가 및 수정 시 이미지가 정상적으로 추가 및 삭제 되도록 변경했습니다.
3. 메뉴 수정 시 카테고리를 1개 이상 넣어야 하도록 변경했습니다.
=> [비즈니스] 이벤트, 메뉴 관련 이슈 수정

src/page/Auth/Signup/view/OwnerDataPage/index.tsx, src/page/ShopRegistration/view/PC/ShopRegistrationPC.module.scss, src/page/ShopRegistration/view/PC/index.tsx, src/query/register.ts, src/store/shopRegistration.ts
- Close #329
- 기능 : 가게 정보기입 에러 수정 및 이미지 등록 과정 수정
- issue : #329
큰 이미지만 보여주는 것이 아닌 회원가입시 등록하는 이미지를 하나씩 보여주는 방식으로 변경하였습니다.
초기 이미지가 깨져나오는 걸 수정했습니다.
=> [가게 정보 기입] 초기 이미지 에러 수정 및 등록 과정 회원가입이랑 동일하게 진행

src/page/Auth/FindPassword/ChangePassword/index.tsx, src/page/Auth/FindPassword/Verify/index.tsx, src/page/Auth/FindPassword/entity.ts, src/page/Auth/FindPassword/index.tsx, src/page/Auth/Signup/components/searchShop/index.tsx, src/page/Auth/Signup/index.tsx, src/page/Auth/components/Common/index.tsx
- Close #355
- 기능 : 비밀번호 찾기 진입오류 수정
- issue : #355
steps 객체로 감싸서 생긴 문제를 해결했습니다.
=> [주변 상점] 비밀번호 찾기 진입오류 수정

src/App.tsx, src/page/Auth/Login/index.tsx, src/page/Auth/components/Common/index.tsx
- 기능 : 비밀번호 sha256으로 해싱
- issue : #
로그인 시 sha256으로 해싱한 비밀번호를 받기 때문에 해싱해서 보내도록 수정
이제 비밀번호 찾기 정상 동작
=> [비즈니스] 비밀번호 sha256으로 해싱

src/page/Auth/hook/useStep.ts
- Close #364 
- 기능 : 가게검색 뒤로가기 버튼 클릭시 가게 정보 입력으로 가도록 변경
- issue : #364
가게검색 뒤로가기 버튼 클릭시 가게 정보 입력으로 가도록 useStep의 previousStep로직 변경
=> [주변상점]가게검색 뒤로가기 버튼 클릭시 가게 정보 입력으로 가도록 변경

src/page/Auth/Signup/components/phoneStep/index.tsx, src/page/Auth/Signup/components/phoneStep/phoneStep.module.scss
- 기능 : 회원가입 인증번호 확인 버튼, 토스트 추가
- issue : #
인증번호 확인을 기존에는 6자리가 되면 자동으로 확인하였지만 확인 버튼으로 확인 할 수 있도록 변경
인증번호 전송, 확인 토스트 추가
=> [비즈니스] 회원가입 인증번호 확인 버튼, 토스트 추가

src/page/Auth/Signup/components/phoneStep/index.tsx
- 기능 : 
- issue : #
폼 재입력시 에러를 초기화해서 유저의 대응에 유연하게 반응했습니다
=> [비즈니스] 폼 재입력시 에러 초기화

src/page/Auth/Login/index.tsx, src/page/MyShopPage/components/BankList/index.tsx, src/page/MyShopPage/components/EditShopInfoModal/index.tsx
- 기능 : 
- issue : #
아이폰 사용자의 경우 비밀번호 인풋에 비밀번호가 자동 추천되는데, 길이가 18자를 넘어서 사용할 수 없는 불편함이 있습니다.
또한 계좌번호 바텀시트 마운트 시 포커스가 바뀌지 않아 크롬 브라우저에서 보기 불편했던 현상을 수정했습니다
=> [비즈니스] 비밀번호 자동완성 막기

src/index.tsx
queryClient에 초기값으로 지정한 staleTime을 제거합니다. 다른 초기값과 동일한 옵션들도 제거합니다.
https://github.com/BCSDLab/KOIN_WEB_RECODE/pull/469 PR과 동일합니다
사이드이펙이 있을 수 있습니다. 기능을 한번씩은 수행해보며 경험을 체크하는게 좋아보입니다
=> refactor: staleTime제거

src/model/shopInfo/allShopInfo.ts, src/page/MyShopPage/components/EditShopInfoModal/index.tsx, src/page/ShopRegistration/component/Modal/Category/index.tsx, src/page/ShopRegistration/view/Mobile/ShopCategory/index.tsx
- 기능 : 상점 생성 및 수정 시 main_category_id 속성 포함
- issue : #
- 상점 생성 및 수정시 zod 상태에 main_category_id가 추가되도록 코드를 수정했습니다.
로직을 적용한 부분은 3 페이지입니다.
1. 상점 수정 모달
2. 초기 상점 생성 PC
3. 초기 상점 생성 모바일
2, 3번은 최초 회원가입 시 나오는 카테고리 부분입니다. 사장님 어플은 기본적으로 카테고리를 한번만 선택 가능해서 메인 카테고리를 동시에 결정하도록 수정하였습니다.
=> [메인 카테고리 추가] : 상점 생성 및 수정 시 메인 카테고리 기능 추가

src/model/shopInfo/allShopInfo.ts, src/model/shopInfo/myShopInfo.ts, src/page/MyShopPage/components/EditShopInfoModal/index.tsx
- 기능 : 
- issue : #
main_category_id가 처음 회원 가입시에는 undefined이기 때문에 optional로 변경했는데 해당 값을 사용하는 곳에서 undefined된 값을 참조해서 에러가 발생하지 않는지 확인 부탁드립니다.
=> fix : main_category_id가 처음 회원 가입시에는 undefined이기 때문에 optional로 변경

src/component/common/Header/index.tsx, src/page/AddMenu/index.tsx, src/page/MyShopPage/components/EditMenu/index.module.scss, src/page/MyShopPage/components/EditMenu/index.tsx, src/page/MyShopPage/components/MenuTable/MenuTable.module.scss, src/page/MyShopPage/components/MenuTable/index.tsx, src/page/ShopRegistration/view/Mobile/Main/index.tsx, src/page/ShopRegistration/view/Mobile/ShopConfirmation/index.tsx, src/page/ShopRegistration/view/Mobile/Sub/index.tsx, src/page/ShopRegistration/view/Mobile/index.tsx, src/page/ShopRegistration/view/PC/ShopConfirmation/index.tsx, src/page/ShopRegistration/view/PC/index.tsx
1. 메뉴 편집 페이지에서 뒤로 가기 관련 문제 해결
2. 메뉴 추가 취소 후 입력값이 남아있는 현상 수정
3. 메뉴 편집 페이지에서 삭제 버튼이 잘리는 현상 수정
4. 가게  등록 단계에서 선택한 카테고리가 제대로 표시되지 않는 현상 수정
5. 가게 등록 단계에서 두 종류의 전화 번호 양식을 입력 받도록 수정
6. 배달비 최댓값 처리
7. 가게 등록 중 이미지 업로드 이후 다음 단계로 갔다가 돌아왔을 때 이미지가 사라지는 현상 수정
=> [비즈니스] 메뉴, 회원가입 관련 최종 수정

src/api/address/index.ts, src/model/shopInfo/address.ts, src/model/shopInfo/ownerShop.ts, src/page/ShopRegistration/component/Modal/AddressSearch/AddressSearch.module.scss, src/page/ShopRegistration/component/Modal/AddressSearch/index.tsx, src/page/ShopRegistration/view/Mobile/Main/index.tsx, src/page/ShopRegistration/view/Mobile/ShopAddress/ShopAddress.module.scss, src/page/ShopRegistration/view/Mobile/ShopAddress/index.tsx, src/page/ShopRegistration/view/Mobile/ShopConfirmation/index.tsx, src/page/ShopRegistration/view/Mobile/index.tsx, src/page/ShopRegistration/view/PC/ShopConfirmation/index.tsx, src/query/KeyFactory/addressKeys.ts, src/query/address.ts
- Close #397
- 기능 : 주소 검증 추가 및 상세 주소 필드 분리
- issue : #397
기존 주소를 문자열로 바로 입력하던 방식에서 외부 API(행정안전부)를 백엔드를 통해 사용해서 검증된 주소를 입력하도록 수정했습니다.
이후 상세 주소를 별도 input으로 입력받도록 분리하였습니다.
스프린트 회의에서 백엔드 수정 여부와 관계없이 프론트에서 미리 필드 분리와 검증 작업을 진행하기로 결정되었습니다.
따라서 현재 API에서는 아직 상세주소를 별도로 받지 않고 있어, 임시로 다시 하나의 address로 합쳐 전달하도록 처리했습니다.
UI 부분 역시 추후 사장님 웹·앱 개편 시 대규모 수정이 예정되어 있어, 현재는 임의로 구현해둔 상태입니다. 해당 내용은 사장님 스프린트가 진행될 때 함께 수정하도록 하겠습니다.
=> [상점 생성] 상점 주소 검증 추가 및 상세 주소 필드 분리
